trigger:
  branches:
    include:
      - main  # The branch to trigger the pipeline

variables:
  resourceGroup: "CloudLabRG"
  planName: "StudentPlan"
  webAppName: "your-unique-app-name"  # Replace with a unique web app name
  location: "centralus"
  runtime: "PYTHON|3.11"

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy Web App to Azure'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Your-Azure-Subscription'  # Use the name of your Azure service connection
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Step 1: Create the App Service Plan
        az appservice plan create \
          --name $(planName) \
          --resource-group $(resourceGroup) \
          --location $(location) \
          --sku F1 \
          --is-linux

        # Step 2: Create the Web App
        az webapp create \
          --resource-group $(resourceGroup) \
          --plan $(planName) \
          --name $(webAppName) \
          --runtime "$(runtime)"
    displayName: 'Create App Service Plan and Web App'
